### ISSUE TITLE
matrix_constr function

### ISSUE THREAD

**Issue by fribalet** [khuntercevera/phyto-division-rate-model#3]
There is an ambiguity in matrix_const function as stasis_ind is shorter than delta:
In matrix_const.m, line 41:    A(stasis_ind)=(1-delta)_(1-y(t+6_hr))
It returns an error message caused by the different length between stasis_ind and delta. Should delta be delta(2:(m-1)) instead?

**Comment by khuntercevera** [comment]
I'm a little confused at this error, because stasis_ind should have the same length as delta (it's pre-allocated based on the length of volbins, which also determines the length of delta, so they should be the same). What were your inputs to matrix_const.m?

**Comment by fribalet** [comment]
it works, stasis_ind was not properly defined in my case.
